const data = {
    products: [
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category: 'Shirts',
            image:'/images/p7.jpg',
            price:10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Nike Slim Shirt',
            category: 'Shirts',
            image:'/images/p2.jpg',
            price:100,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Lacoste Free Shirt',
            category: 'Shirts',
            image:'/images/p8.jpg',
            price:220,
            brand: 'Lacoste',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Adidas Slim Pants',
            category: 'Shirts',
            image:'/images/p4.jpg',
            price:1120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Puma Slim Pants',
            category: 'Shirts',
            image:'/images/p5.jpg',
            price:160,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Adidas Fit Pants',
            category: 'Shirts',
            image:'/images/p9.jpg',
            price:110,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        }
    ]
}

export default data;